In [25]:
import pywt
import random
import time
import numpy as np

In [26]:
N = 100
idx = 0
res_list = []

In [27]:
for _ in range(N):
    res_list.append(np.sin(idx))
    idx += 0.1

In [28]:
# x = [random.randint(0,100) for _ in range(N)]

In [29]:
# start = time.time()
# coeffs=pywt.wavedec(x, 'db1', level = 25, mode = 'periodic')
# print(time.time() - start)

In [32]:
start = time.time()
coeffs=pywt.wavedec(res_list, 'db1', level = 4, mode = 'periodic')
print(time.time() - start)

0.0009207725524902344


In [33]:
coeffs

[array([ 2.44590758,  2.55296232, -2.59499814, -2.4014169 ,  2.7352386 ,
         2.24168158,  0.49891188]),
 array([-1.11004408,  1.06608495,  1.04778574, -1.12727464, -0.98195398,
         1.18461981, -0.83695162]),
 array([-0.52456048, -0.2281058 ,  0.20671479,  0.51614497,  0.51248853,
         0.19796343, -0.23664363, -0.52770584, -0.49866877, -0.16714591,
         0.26576541,  0.537467  , -0.65906785]),
 array([-0.19717806, -0.17000814, -0.11599767, -0.04367372,  0.03554535,
         0.10915259,  0.16552704,  0.1957684 ,  0.19510225,  0.16363373,
         0.10633105,  0.03224103, -0.04693913, -0.11870864, -0.17173667,
        -0.19765125, -0.19236105, -0.15670126, -0.09630179, -0.02069839,
         0.05817283,  0.12785985,  0.1773606 ,  0.19886002,  0.18896381]),
 array([-0.07059289, -0.06848391, -0.0636447 , -0.05626817, -0.04664841,
        -0.03516893, -0.02228737, -0.00851728,  0.00559236,  0.01947905,
         0.03258918,  0.04440008,  0.05444088,  0.0623113 ,  0.06769757,
 